### ISSUE TITLE
Fails to generate when using Windows

### ISSUE THREAD

**Issue by FormallyMyles** [yawkat/mdep#1]
I'm using spring boot & maven.

http://hastebin.com/fehiqikabo.avrasm

You can find the project here, https://github.com/Matsv/PAaaS/ if needed. (But you would need to add the plugin & loader)

Just putting this as an issue so it's tracked.

**Comment by yawkat** [comment]
Would appreciate a test of this fix on windows, since I don't have an installation available, before I release this to central

**Comment by FormallyMyles** [comment]
@yawkat Compiles fine :+1: good job
